""" Updated Table

Revision ID: 0ab59c6f5ead
Revises: c3c4c8ef0927
Create Date: 2023-09-05 22:04:04.043602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ab59c6f5ead'
down_revision: Union[str, None] = 'c3c4c8ef0927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
